-- ============================================================
-- MedQuote Pro — إدارة الكيماويات: مسودة مواصفات الفحص (COA)
-- مواصفات نموذجية لدرجة المختبر (LR) لكل مادة — تُعلَّم "بانتظار المراجعة"
-- (chem_materials.specs_reviewed = false) لحد ما مسؤول المختبر يراجعها ويعدّلها
-- حسب COA المصنّع ودرجة المادة الفعلية.
-- يُضاف فقط للمواد اللي ما إلها أي بند مواصفات — ما بيلمس شي عدّلته.
-- يُشغَّل بعد chemicals_seed.sql. آمن لإعادة التشغيل.
-- ============================================================

BEGIN;

ALTER TABLE public.chem_materials ADD COLUMN IF NOT EXISTS specs_reviewed boolean NOT NULL DEFAULT true;

CREATE TEMP TABLE _draft_specs (name text, seq int, parameter text, spec_type text, min_value numeric, max_value numeric, text_value text, unit text, method text) ON COMMIT DROP;
INSERT INTO _draft_specs VALUES
  ('1-Propanol', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('1-Propanol', 1, 'Assay', 'min', 99.5, NULL, NULL, '%', 'GC'),
  ('1-Propanol', 2, 'Water', 'max', NULL, 0.2, NULL, '%', 'Karl Fischer'),
  ('1-Propanol', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('2,6-Dichlorophenolindophenol Sodium Salt (DCPIP)', 0, 'Appearance', 'text', NULL, NULL, 'Dark green to black powder', NULL, 'Visual'),
  ('2,6-Dichlorophenolindophenol Sodium Salt (DCPIP)', 1, 'Solubility', 'text', NULL, NULL, 'Clear solution in ethanol / water', NULL, 'Visual'),
  ('2,6-Dichlorophenolindophenol Sodium Salt (DCPIP)', 2, 'Transition interval', 'text', NULL, NULL, 'Blue (oxidised) → colourless on reduction by ascorbic acid', NULL, 'pH titration'),
  ('Gum Arabic (Acacia)', 0, 'Appearance', 'text', NULL, NULL, 'White to yellowish-white powder', NULL, 'Visual'),
  ('Gum Arabic (Acacia)', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Acetaldehyde', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Acetaldehyde', 1, 'Assay', 'min', 99.0, NULL, NULL, '%', 'GC'),
  ('Acetaldehyde', 2, 'Water', 'max', NULL, 0.5, NULL, '%', 'Karl Fischer'),
  ('Acetaldehyde', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('Acetic Acid', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Acetic Acid', 1, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Acetone', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Acetone', 1, 'Assay', 'min', 99.5, NULL, NULL, '%', 'GC'),
  ('Acetone', 2, 'Water', 'max', NULL, 0.5, NULL, '%', 'Karl Fischer'),
  ('Acetone', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('Acid-Fast Stain Kit (Ziehl-Neelsen)', 0, 'Appearance', 'text', NULL, NULL, 'Complete kit: carbol fuchsin, acid-alcohol, methylene blue', NULL, 'Visual'),
  ('Acid-Fast Stain Kit (Ziehl-Neelsen)', 1, 'Components', 'text', NULL, NULL, 'All components present and labelled', NULL, 'Visual'),
  ('Acid-Fast Stain Kit (Ziehl-Neelsen)', 2, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Activated Carbon', 0, 'Appearance', 'text', NULL, NULL, 'Black fine powder', NULL, 'Visual'),
  ('Activated Carbon', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Activated Carbon', 2, 'Loss on drying', 'max', NULL, 10.0, NULL, '%', 'Gravimetric'),
  ('Activated Carbon', 3, 'Residue on ignition', 'max', NULL, 5.0, NULL, '%', 'Gravimetric'),
  ('Alpha-Naphthol Solution 5%', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless to pale yellow solution', NULL, 'Visual'),
  ('Alpha-Naphthol Solution 5%', 1, 'alpha-Naphthol', 'range', 4.8, 5.2, NULL, '% w/v', 'Gravimetric'),
  ('Aluminium Oxide', 0, 'Appearance', 'text', NULL, NULL, 'White powder', NULL, 'Visual'),
  ('Aluminium Oxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Aluminium Oxide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Aluminium Oxide', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Aluminium Oxide', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Aluminium Potassium Sulfate Dodecahydrate (Potash Alum)', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Aluminium Potassium Sulfate Dodecahydrate (Potash Alum)', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Aluminium Potassium Sulfate Dodecahydrate (Potash Alum)', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Aluminium Potassium Sulfate Dodecahydrate (Potash Alum)', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Aluminium Potassium Sulfate Dodecahydrate (Potash Alum)', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Aluminium Hydroxide', 0, 'Appearance', 'text', NULL, NULL, 'White powder', NULL, 'Visual'),
  ('Aluminium Hydroxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Aluminium Hydroxide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Aluminium Hydroxide', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Aluminium Hydroxide', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Ammonia Solution', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Ammonia Solution', 1, 'Assay (NH3)', 'range', 25.0, 28.0, NULL, '%', 'Titration'),
  ('Ammonium Oxalate Monohydrate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Ammonium Oxalate Monohydrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Ammonium Oxalate Monohydrate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Ammonium Oxalate Monohydrate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Ammonium Oxalate Monohydrate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Ammonium Chloride', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Ammonium Chloride', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Ammonium Chloride', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Ammonium Chloride', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Ammonium Chloride', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Ammonium Dichromate', 0, 'Appearance', 'text', NULL, NULL, 'Orange-red crystals', NULL, 'Visual'),
  ('Ammonium Dichromate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Ammonium Dichromate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Ammonium Dichromate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Ammonium Dichromate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Ammonium Sulfate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Ammonium Sulfate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Ammonium Sulfate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Ammonium Sulfate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Ammonium Sulfate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Ammonium Thiocyanate', 0, 'Appearance', 'text', NULL, NULL, 'Colourless to white crystals', NULL, 'Visual'),
  ('Ammonium Thiocyanate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Ammonium Thiocyanate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Ammonium Thiocyanate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Ammonium Thiocyanate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Arachis Oil (Peanut Oil)', 0, 'Appearance', 'text', NULL, NULL, 'Clear pale yellow oil', NULL, 'Visual'),
  ('Arachis Oil (Peanut Oil)', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Ascorbic Acid', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Ascorbic Acid', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Ascorbic Acid', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Barium Hydroxide', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Barium Hydroxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Barium Hydroxide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Barium Hydroxide', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Barium Oxide', 0, 'Appearance', 'text', NULL, NULL, 'White to greyish powder', NULL, 'Visual'),
  ('Barium Oxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Barium Oxide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Barium Oxide', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Barium Carbonate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Barium Carbonate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Barium Carbonate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Barium Carbonate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Barium Sulfate', 0, 'Appearance', 'text', NULL, NULL, 'White fine powder', NULL, 'Visual'),
  ('Barium Sulfate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Barium Sulfate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Barium Sulfate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Barium Nitrate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Barium Nitrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Barium Nitrate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Barium Nitrate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Benedict''s Reagent', 0, 'Appearance', 'text', NULL, NULL, 'Clear blue solution', NULL, 'Visual'),
  ('Benedict''s Reagent', 1, 'Performance (0.5 % glucose)', 'text', NULL, NULL, 'Brick-red precipitate — positive; blank negative', NULL, 'In-house'),
  ('Benzoic Acid', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Benzoic Acid', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Benzoic Acid', 2, 'Assay', 'min', 99.5, NULL, NULL, '%', 'Titration'),
  ('Benzoic Acid', 3, 'Melting point', 'range', 121.0, 124.0, NULL, '°C', 'Melting point apparatus'),
  ('Biuret Reagent', 0, 'Appearance', 'text', NULL, NULL, 'Clear blue solution', NULL, 'Visual'),
  ('Biuret Reagent', 1, 'Performance (albumin)', 'text', NULL, NULL, 'Violet colour — passes', NULL, 'In-house'),
  ('Bromine Water', 0, 'Appearance', 'text', NULL, NULL, 'Clear yellow-orange solution', NULL, 'Visual'),
  ('Bromine Water', 1, 'Performance (alkene decolourisation)', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Buffer Solution pH 6.0', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless solution', NULL, 'Visual'),
  ('Buffer Solution pH 6.0', 1, 'pH at 25 °C', 'range', 5.95, 6.05, NULL, '', 'pH meter'),
  ('Calcium Nitrate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Calcium Nitrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Calcium Nitrate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Calcium Nitrate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Calcium Nitrate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Calcium Oxide', 0, 'Appearance', 'text', NULL, NULL, 'White lumps or powder', NULL, 'Visual'),
  ('Calcium Oxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Calcium Oxide', 2, 'Assay', 'min', 95.0, NULL, NULL, '%', 'Titration'),
  ('Calcium Oxide', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Calcium Oxide', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Cobalt(II) Chloride Hexahydrate', 0, 'Appearance', 'text', NULL, NULL, 'Red to purple crystals', NULL, 'Visual'),
  ('Cobalt(II) Chloride Hexahydrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Cobalt(II) Chloride Hexahydrate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Cobalt(II) Chloride Hexahydrate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Copper(I) Iodide', 0, 'Appearance', 'text', NULL, NULL, 'White to off-white powder', NULL, 'Visual'),
  ('Copper(I) Iodide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Copper(I) Iodide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Copper(I) Iodide', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Copper(II) Nitrate', 0, 'Appearance', 'text', NULL, NULL, 'Blue crystals', NULL, 'Visual'),
  ('Copper(II) Nitrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Copper(II) Nitrate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Copper(II) Nitrate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Cyclohexane', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Cyclohexane', 1, 'Assay', 'min', 99.5, NULL, NULL, '%', 'GC'),
  ('Cyclohexane', 2, 'Water', 'max', NULL, 0.02, NULL, '%', 'Karl Fischer'),
  ('Cyclohexane', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('Cadmium Oxalate Trihydrate', 0, 'Appearance', 'text', NULL, NULL, 'White powder', NULL, 'Visual'),
  ('Cadmium Oxalate Trihydrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Cadmium Oxalate Trihydrate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Cadmium Oxalate Trihydrate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Calcium Acetate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Calcium Acetate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Calcium Acetate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Calcium Acetate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Calcium Acetate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Calcium Carbide', 0, 'Appearance', 'text', NULL, NULL, 'Grey-black lumps', NULL, 'Visual'),
  ('Calcium Carbide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Calcium Carbide', 2, 'Gas evolution with water', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Calcium Carbonate Precipitated', 0, 'Appearance', 'text', NULL, NULL, 'White fine powder', NULL, 'Visual'),
  ('Calcium Carbonate Precipitated', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Calcium Carbonate Precipitated', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Calcium Carbonate Precipitated', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Calcium Carbonate Precipitated', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Calcium Chloride Fused (Anhydrous)', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Calcium Chloride Fused (Anhydrous)', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Calcium Chloride Fused (Anhydrous)', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Calcium Chloride Fused (Anhydrous)', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Calcium Chloride Fused (Anhydrous)', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Calcium Lactate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Calcium Lactate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Calcium Lactate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Calcium Lactate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Calcium Lactate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Calcium Metal', 0, 'Appearance', 'text', NULL, NULL, 'Silvery-grey granules / turnings', NULL, 'Visual'),
  ('Calcium Metal', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Calcium Metal', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'In-house'),
  ('Calcium Chloride Dihydrate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Calcium Chloride Dihydrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Calcium Chloride Dihydrate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Calcium Chloride Dihydrate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Calcium Chloride Dihydrate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Calcium Hydroxide', 0, 'Appearance', 'text', NULL, NULL, 'White fine powder', NULL, 'Visual'),
  ('Calcium Hydroxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Calcium Hydroxide', 2, 'Assay', 'min', 95.0, NULL, NULL, '%', 'Titration'),
  ('Calcium Hydroxide', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Calcium Hydroxide', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Capsule Stain Kit (Anthony''s)', 0, 'Appearance', 'text', NULL, NULL, 'Complete kit: crystal violet 1 %, copper sulfate 20 %', NULL, 'Visual'),
  ('Capsule Stain Kit (Anthony''s)', 1, 'Components', 'text', NULL, NULL, 'All components present and labelled', NULL, 'Visual'),
  ('Capsule Stain Kit (Anthony''s)', 2, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Carbol Fuchsin Solution', 0, 'Appearance', 'text', NULL, NULL, 'Clear deep red solution', NULL, 'Visual'),
  ('Carbol Fuchsin Solution', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Carbon Tetrachloride', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Carbon Tetrachloride', 1, 'Assay', 'min', 99.5, NULL, NULL, '%', 'GC'),
  ('Carbon Tetrachloride', 2, 'Water', 'max', NULL, 0.02, NULL, '%', 'Karl Fischer'),
  ('Carbon Tetrachloride', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('Chloroform', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Chloroform', 1, 'Assay', 'min', 99.0, NULL, NULL, '%', 'GC'),
  ('Chloroform', 2, 'Water', 'max', NULL, 0.05, NULL, '%', 'Karl Fischer'),
  ('Chloroform', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('Chromium(VI) Oxide (Chromium Trioxide)', 0, 'Appearance', 'text', NULL, NULL, 'Dark red flakes / crystals', NULL, 'Visual'),
  ('Chromium(VI) Oxide (Chromium Trioxide)', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Chromium(VI) Oxide (Chromium Trioxide)', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Chromium(VI) Oxide (Chromium Trioxide)', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Citric Acid', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Citric Acid', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Citric Acid', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Citric Acid', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Citric Acid', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Copper(II) Chloride Dihydrate', 0, 'Appearance', 'text', NULL, NULL, 'Blue-green crystals', NULL, 'Visual'),
  ('Copper(II) Chloride Dihydrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Copper(II) Chloride Dihydrate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Copper(II) Chloride Dihydrate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Copper(II) Oxide', 0, 'Appearance', 'text', NULL, NULL, 'Black powder', NULL, 'Visual'),
  ('Copper(II) Oxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Copper(II) Oxide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Copper(II) Oxide', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Copper(II) Sulfate Anhydrous', 0, 'Appearance', 'text', NULL, NULL, 'White to greyish-white powder', NULL, 'Visual'),
  ('Copper(II) Sulfate Anhydrous', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Copper(II) Sulfate Anhydrous', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Copper(II) Sulfate Anhydrous', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Copper(II) Sulfate Pentahydrate', 0, 'Appearance', 'text', NULL, NULL, 'Blue crystals or crystalline powder', NULL, 'Visual'),
  ('Copper(II) Sulfate Pentahydrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Copper(II) Sulfate Pentahydrate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Copper(II) Sulfate Pentahydrate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Counter Stain (Safranin)', 0, 'Appearance', 'text', NULL, NULL, 'Clear red solution', NULL, 'Visual'),
  ('Counter Stain (Safranin)', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Crystal Violet', 0, 'Appearance', 'text', NULL, NULL, 'Dark green crystalline powder with metallic lustre', NULL, 'Visual'),
  ('Crystal Violet', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('D-Sorbitol', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('D-Sorbitol', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('D-Sorbitol', 2, 'Assay', 'min', 97.0, NULL, NULL, '%', 'HPLC'),
  ('D-Sorbitol', 3, 'Water', 'max', NULL, 1.0, NULL, '%', 'Karl Fischer'),
  ('Decolorizer Solution (Acetone-Alcohol)', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Decolorizer Solution (Acetone-Alcohol)', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Diethyl Ether', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Diethyl Ether', 1, 'Assay', 'min', 99.5, NULL, NULL, '%', 'GC'),
  ('Diethyl Ether', 2, 'Water', 'max', NULL, 0.05, NULL, '%', 'Karl Fischer'),
  ('Diethyl Ether', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('Emulsifying Wax', 0, 'Appearance', 'text', NULL, NULL, 'White to off-white waxy flakes', NULL, 'Visual'),
  ('Emulsifying Wax', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Eosin Y Stain', 0, 'Appearance', 'text', NULL, NULL, 'Clear red-orange solution', NULL, 'Visual'),
  ('Eosin Y Stain', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Ethanol Absolute', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Ethanol Absolute', 1, 'Assay', 'min', 99.5, NULL, NULL, '%', 'GC'),
  ('Ethanol Absolute', 2, 'Water', 'max', NULL, 0.3, NULL, '%', 'Karl Fischer'),
  ('Ethanol Absolute', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('Ethyl Acetate', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Ethyl Acetate', 1, 'Assay', 'min', 99.5, NULL, NULL, '%', 'GC'),
  ('Ethyl Acetate', 2, 'Water', 'max', NULL, 0.1, NULL, '%', 'Karl Fischer'),
  ('Ethyl Acetate', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('Methyl Ethyl Ketone (2-Butanone)', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Methyl Ethyl Ketone (2-Butanone)', 1, 'Assay', 'min', 99.5, NULL, NULL, '%', 'GC'),
  ('Methyl Ethyl Ketone (2-Butanone)', 2, 'Water', 'max', NULL, 0.1, NULL, '%', 'Karl Fischer'),
  ('Methyl Ethyl Ketone (2-Butanone)', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('Fehling''s Solution A', 0, 'Appearance', 'text', NULL, NULL, 'Clear blue solution', NULL, 'Visual'),
  ('Fehling''s Solution A', 1, 'CuSO4·5H2O', 'range', 6.83, 7.03, NULL, '% w/v', 'Titration'),
  ('Gentian Violet', 0, 'Appearance', 'text', NULL, NULL, 'Dark green powder with metallic lustre', NULL, 'Visual'),
  ('Gentian Violet', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Glycerol', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless viscous liquid', NULL, 'Visual'),
  ('Glycerol', 1, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Glycerol', 2, 'Water', 'max', NULL, 1.0, NULL, '%', 'Karl Fischer'),
  ('Gram Stain Kit', 0, 'Appearance', 'text', NULL, NULL, 'Complete kit: crystal violet, Gram''s iodine, decolorizer, safranin', NULL, 'Visual'),
  ('Gram Stain Kit', 1, 'Components', 'text', NULL, NULL, 'All components present and labelled', NULL, 'Visual'),
  ('Gram Stain Kit', 2, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Gram''s Iodine', 0, 'Appearance', 'text', NULL, NULL, 'Clear brown solution', NULL, 'Visual'),
  ('Gram''s Iodine', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Hydrogen Peroxide', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Hydrogen Peroxide', 1, 'Assay (H2O2)', 'text', NULL, NULL, 'As stated on label ± 5 % (relative)', NULL, 'Titration (KMnO4)'),
  ('India Ink', 0, 'Appearance', 'text', NULL, NULL, 'Black opaque suspension', NULL, 'Visual'),
  ('India Ink', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Indigo Carmine', 0, 'Appearance', 'text', NULL, NULL, 'Dark blue powder', NULL, 'Visual'),
  ('Indigo Carmine', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Iodine Crystals', 0, 'Appearance', 'text', NULL, NULL, 'Violet-black crystals with metallic lustre', NULL, 'Visual'),
  ('Iodine Crystals', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Iodine Crystals', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Iodine Crystals', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Iodine Crystals', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Iron(III) Nitrate', 0, 'Appearance', 'text', NULL, NULL, 'Pale violet to colourless crystals', NULL, 'Visual'),
  ('Iron(III) Nitrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Iron(III) Nitrate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Iron(III) Nitrate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Iron(III) Chloride Anhydrous', 0, 'Appearance', 'text', NULL, NULL, 'Dark green-black crystals', NULL, 'Visual'),
  ('Iron(III) Chloride Anhydrous', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Iron(III) Chloride Anhydrous', 2, 'Assay', 'min', 97.0, NULL, NULL, '%', 'Titration'),
  ('Iron(III) Chloride Anhydrous', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Iron(III) Chloride Hexahydrate', 0, 'Appearance', 'text', NULL, NULL, 'Yellow-brown crystalline lumps', NULL, 'Visual'),
  ('Iron(III) Chloride Hexahydrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Iron(III) Chloride Hexahydrate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Iron(III) Chloride Hexahydrate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Isopropyl Alcohol', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Isopropyl Alcohol', 1, 'Assay', 'min', 99.5, NULL, NULL, '%', 'GC'),
  ('Isopropyl Alcohol', 2, 'Water', 'max', NULL, 0.2, NULL, '%', 'Karl Fischer'),
  ('Isopropyl Alcohol', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('Kovac''s Reagent', 0, 'Appearance', 'text', NULL, NULL, 'Clear yellow liquid', NULL, 'Visual'),
  ('Kovac''s Reagent', 1, 'Performance (indole, E. coli)', 'text', NULL, NULL, 'Red ring — positive', NULL, 'In-house'),
  ('Lead(II) Bromide', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Lead(II) Bromide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Lead(II) Bromide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Lead(II) Bromide', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Lead(II) Nitrate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Lead(II) Nitrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Lead(II) Nitrate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Lead(II) Nitrate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Lead(II) Sulfate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Lead(II) Sulfate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Lead(II) Sulfate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Lead(II) Sulfate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Lithium Bromide Anhydrous', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Lithium Bromide Anhydrous', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Lithium Bromide Anhydrous', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Lithium Bromide Anhydrous', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Lithium Bromide Anhydrous', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Lithium Chloride', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Lithium Chloride', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Lithium Chloride', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Lithium Chloride', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Lithium Chloride', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Litmus Solution Blue', 0, 'Appearance', 'text', NULL, NULL, 'Clear blue-violet solution', NULL, 'Visual'),
  ('Litmus Solution Blue', 1, 'Transition interval', 'text', NULL, NULL, 'Turns red in acid (pH < 4.5)', NULL, 'pH titration'),
  ('Litmus Solution Red', 0, 'Appearance', 'text', NULL, NULL, 'Clear red solution', NULL, 'Visual'),
  ('Litmus Solution Red', 1, 'Transition interval', 'text', NULL, NULL, 'Turns blue in alkali (pH > 8.3)', NULL, 'pH titration'),
  ('Lugol''s Iodine', 0, 'Appearance', 'text', NULL, NULL, 'Clear dark brown solution', NULL, 'Visual'),
  ('Lugol''s Iodine', 1, 'Iodine (I2)', 'range', 4.5, 5.5, NULL, '% w/v', 'Titration'),
  ('Methyl Red', 0, 'Appearance', 'text', NULL, NULL, 'Dark red crystalline powder', NULL, 'Visual'),
  ('Methyl Red', 1, 'Solubility', 'text', NULL, NULL, 'Clear solution in ethanol / water', NULL, 'Visual'),
  ('Methyl Red', 2, 'Transition interval', 'text', NULL, NULL, 'pH 4.4 (red) – 6.2 (yellow)', NULL, 'pH titration'),
  ('Magnesium Chloride', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Magnesium Chloride', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Magnesium Chloride', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Magnesium Chloride', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Magnesium Chloride', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Magnesium Sulfate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Magnesium Sulfate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Magnesium Sulfate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Magnesium Sulfate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Magnesium Sulfate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Magnesium Nitrate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Magnesium Nitrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Magnesium Nitrate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Magnesium Nitrate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Magnesium Nitrate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Magnesium Oxide', 0, 'Appearance', 'text', NULL, NULL, 'White fine powder', NULL, 'Visual'),
  ('Magnesium Oxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Magnesium Oxide', 2, 'Assay', 'min', 97.0, NULL, NULL, '%', 'Titration'),
  ('Magnesium Oxide', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Magnesium Oxide', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Malachite Green', 0, 'Appearance', 'text', NULL, NULL, 'Green crystals with metallic lustre', NULL, 'Visual'),
  ('Malachite Green', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Marble Chips', 0, 'Appearance', 'text', NULL, NULL, 'White to off-white chips', NULL, 'Visual'),
  ('Marble Chips', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Marble Chips', 2, 'Assay (CaCO3)', 'min', 95.0, NULL, NULL, '%', 'Titration'),
  ('Mercury(II) Chloride', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Mercury(II) Chloride', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Mercury(II) Chloride', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Mercury(II) Chloride', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Methanol', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Methanol', 1, 'Assay', 'min', 99.5, NULL, NULL, '%', 'GC'),
  ('Methanol', 2, 'Water', 'max', NULL, 0.1, NULL, '%', 'Karl Fischer'),
  ('Methanol', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('Methyl Blue', 0, 'Appearance', 'text', NULL, NULL, 'Dark blue powder', NULL, 'Visual'),
  ('Methyl Blue', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Millon''s Reagent', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless to pale yellow solution', NULL, 'Visual'),
  ('Millon''s Reagent', 1, 'Performance (protein)', 'text', NULL, NULL, 'Red colour — passes', NULL, 'In-house'),
  ('Naphthalene', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline flakes, characteristic odour', NULL, 'Visual'),
  ('Naphthalene', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Naphthalene', 2, 'Melting point', 'range', 79.0, 81.0, NULL, '°C', 'Melting point apparatus'),
  ('Naphthalene', 3, 'Assay', 'min', 99.0, NULL, NULL, '%', 'GC'),
  ('Nickel(II) Chloride', 0, 'Appearance', 'text', NULL, NULL, 'Green crystals', NULL, 'Visual'),
  ('Nickel(II) Chloride', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Nickel(II) Chloride', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Nickel(II) Chloride', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Nitric Acid', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless to faintly yellow liquid', NULL, 'Visual'),
  ('Nitric Acid', 1, 'Assay (HNO3)', 'min', 65.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Chromate', 0, 'Appearance', 'text', NULL, NULL, 'Yellow crystals', NULL, 'Visual'),
  ('Potassium Chromate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Chromate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Chromate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Potassium Dichromate', 0, 'Appearance', 'text', NULL, NULL, 'Orange-red crystals', NULL, 'Visual'),
  ('Potassium Dichromate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Dichromate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Dichromate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Potassium Dichromate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Potassium Sulfate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Potassium Sulfate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Sulfate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Sulfate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Potassium Sulfate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Peppermint Oil', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless to pale yellow oil, characteristic odour', NULL, 'Visual'),
  ('Peppermint Oil', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Petroleum Ether 60-80 °C', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Petroleum Ether 60-80 °C', 1, 'Boiling range', 'range', 60, 80, NULL, '°C', 'Distillation'),
  ('Petroleum Ether 60-80 °C', 2, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('Phenol', 0, 'Appearance', 'text', NULL, NULL, 'Colourless to pale pink crystals', NULL, 'Visual'),
  ('Phenol', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Phenol', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Phenol', 3, 'Melting point', 'range', 39.0, 42.0, NULL, '°C', 'Melting point apparatus'),
  ('Polyethylene Glycol (PEG)', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless viscous liquid', NULL, 'Visual'),
  ('Polyethylene Glycol (PEG)', 1, 'Grade', 'text', NULL, NULL, 'As stated on label (MW)', NULL, 'In-house'),
  ('Potassium Chloride', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Potassium Chloride', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Chloride', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Chloride', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Potassium Chloride', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Potassium Ferricyanide', 0, 'Appearance', 'text', NULL, NULL, 'Red crystals', NULL, 'Visual'),
  ('Potassium Ferricyanide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Ferricyanide', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Ferricyanide', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Potassium Ferricyanide', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Potassium Hydrogen Phthalate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Potassium Hydrogen Phthalate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Hydrogen Phthalate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Hydroxide', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Potassium Hydroxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Hydroxide', 2, 'Assay (KOH)', 'min', 85.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Hydroxide', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Potassium Hydroxide', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Potassium Hydroxide Solution', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless solution', NULL, 'Visual'),
  ('Potassium Hydroxide Solution', 1, 'Concentration', 'range', 0.98, 1.02, NULL, 'mol/L', 'Titration (HCl)'),
  ('Potassium Iodate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Potassium Iodate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Iodate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Iodate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Potassium Iodate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Potassium Iodide', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Potassium Iodide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Iodide', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Iodide', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Potassium Iodide', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Potassium Permanganate', 0, 'Appearance', 'text', NULL, NULL, 'Dark purple crystals with metallic lustre', NULL, 'Visual'),
  ('Potassium Permanganate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Permanganate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Permanganate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Potassium Permanganate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Potassium Bisulfate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Potassium Bisulfate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Bisulfate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Bisulfate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Potassium Bisulfate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Potassium Bicarbonate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Potassium Bicarbonate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Bicarbonate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Bicarbonate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Potassium Bicarbonate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Potassium Carbonate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Potassium Carbonate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Carbonate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Carbonate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Potassium Carbonate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Potassium Chloride Solution', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless solution', NULL, 'Visual'),
  ('Potassium Chloride Solution', 1, 'Concentration', 'range', 0.98, 1.02, NULL, 'mol/L', 'Titration (AgNO3)'),
  ('Potassium Nitrate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Potassium Nitrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Nitrate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Nitrate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Potassium Nitrate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Propylene Glycol', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless viscous liquid', NULL, 'Visual'),
  ('Propylene Glycol', 1, 'Assay', 'min', 99.5, NULL, NULL, '%', 'GC'),
  ('Quinine Sulfate', 0, 'Appearance', 'text', NULL, NULL, 'White fine crystalline powder', NULL, 'Visual'),
  ('Quinine Sulfate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Quinine Sulfate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Red Food Color', 0, 'Appearance', 'text', NULL, NULL, 'Red liquid', NULL, 'Visual'),
  ('Red Food Color', 1, 'Colour', 'text', NULL, NULL, 'Conforms to standard', NULL, 'Visual'),
  ('Sabouraud Dextrose Agar (SDA)', 0, 'Appearance', 'text', NULL, NULL, 'Light yellow free-flowing powder', NULL, 'Visual'),
  ('Sabouraud Dextrose Agar (SDA)', 1, 'pH of prepared medium (25 °C)', 'range', 5.4, 5.8, NULL, '', 'pH meter'),
  ('Sabouraud Dextrose Agar (SDA)', 2, 'Growth promotion', 'text', NULL, NULL, 'Good growth of C. albicans and A. brasiliensis', NULL, 'Microbiological'),
  ('Sabouraud Dextrose Agar (SDA)', 3, 'Sterility (prepared medium)', 'text', NULL, NULL, 'No growth', NULL, 'Incubation'),
  ('Safranin Stain', 0, 'Appearance', 'text', NULL, NULL, 'Clear red solution', NULL, 'Visual'),
  ('Safranin Stain', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Salicylic Acid', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Salicylic Acid', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Salicylic Acid', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Salicylic Acid', 3, 'Melting point', 'range', 158.0, 161.0, NULL, '°C', 'Melting point apparatus'),
  ('Silicon Dioxide', 0, 'Appearance', 'text', NULL, NULL, 'White powder', NULL, 'Visual'),
  ('Silicon Dioxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Silicon Dioxide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Silicon Dioxide', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Silicon Dioxide', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sodium Bisulfite', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Bisulfite', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Bisulfite', 2, 'Assay (as SO2)', 'min', 58.5, NULL, NULL, '%', 'Iodometric titration'),
  ('Sodium Bisulfite', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sodium Bisulfite', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sodium Metabisulfite', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Metabisulfite', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Metabisulfite', 2, 'Assay', 'min', 97.0, NULL, NULL, '%', 'Titration'),
  ('Sodium Metabisulfite', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sodium Metabisulfite', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sodium Oxalate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Oxalate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Oxalate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Sodium Oxalate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sodium Oxalate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Trisodium Phosphate Hydrate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Trisodium Phosphate Hydrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Trisodium Phosphate Hydrate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Trisodium Phosphate Hydrate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Trisodium Phosphate Hydrate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sodium Thiocyanate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Thiocyanate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Thiocyanate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Sodium Thiocyanate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sodium Thiocyanate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Stearic Acid', 0, 'Appearance', 'text', NULL, NULL, 'White waxy flakes / powder', NULL, 'Visual'),
  ('Stearic Acid', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Stearic Acid', 2, 'Melting point', 'range', 54.0, 69.0, NULL, '°C', 'Melting point apparatus'),
  ('Strontium Carbonate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Strontium Carbonate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Strontium Carbonate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Strontium Carbonate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Silver Metal', 0, 'Appearance', 'text', NULL, NULL, 'Silvery-white metal', NULL, 'Visual'),
  ('Silver Metal', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Silver Metal', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'In-house'),
  ('Silver Nitrate', 0, 'Appearance', 'text', NULL, NULL, 'Colourless to white crystals', NULL, 'Visual'),
  ('Silver Nitrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Silver Nitrate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Silver Nitrate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sodium Alginate', 0, 'Appearance', 'text', NULL, NULL, 'White to yellowish-brown powder', NULL, 'Visual'),
  ('Sodium Alginate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Alginate', 2, 'Loss on drying', 'max', NULL, 15.0, NULL, '%', 'Gravimetric'),
  ('Sodium Carbonate Anhydrous', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Carbonate Anhydrous', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Carbonate Anhydrous', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Sodium Carbonate Anhydrous', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sodium Carbonate Anhydrous', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sodium Chloride', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Chloride', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Chloride', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Sodium Chloride', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sodium Chloride', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Trisodium Citrate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Trisodium Citrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Trisodium Citrate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Trisodium Citrate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Trisodium Citrate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sodium Fluoride', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Fluoride', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Fluoride', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Sodium Fluoride', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sodium Fluoride', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sodium Hydrogen Carbonate (Sodium Bicarbonate)', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Hydrogen Carbonate (Sodium Bicarbonate)', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Hydrogen Carbonate (Sodium Bicarbonate)', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Sodium Hydrogen Carbonate (Sodium Bicarbonate)', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sodium Hydrogen Carbonate (Sodium Bicarbonate)', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sodium Hydroxide', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Hydroxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Hydroxide', 2, 'Assay (NaOH)', 'min', 97.0, NULL, NULL, '%', 'Titration'),
  ('Sodium Hydroxide', 3, 'Carbonate (as Na2CO3)', 'max', NULL, 1.0, NULL, '%', 'Titration'),
  ('Sodium Hydroxide', 4, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sodium Hydroxide', 5, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sodium Hydroxide Solution', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless solution', NULL, 'Visual'),
  ('Sodium Hydroxide Solution', 1, 'Concentration', 'range', 0.98, 1.02, NULL, 'mol/L', 'Titration (KHP)'),
  ('Sodium Lauryl Sulfate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Lauryl Sulfate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Lauryl Sulfate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Sodium Silicate', 0, 'Appearance', 'text', NULL, NULL, 'Clear viscous liquid', NULL, 'Visual'),
  ('Sodium Silicate', 1, 'SiO2 / Na2O content', 'text', NULL, NULL, 'As stated on label', NULL, 'Titration'),
  ('Sodium Sulfate Anhydrous', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Sulfate Anhydrous', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Sulfate Anhydrous', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Sodium Sulfate Anhydrous', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sodium Sulfate Anhydrous', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sodium Hypochlorite Solution', 0, 'Appearance', 'text', NULL, NULL, 'Clear greenish-yellow liquid', NULL, 'Visual'),
  ('Sodium Hypochlorite Solution', 1, 'Available chlorine', 'text', NULL, NULL, 'As stated on label', NULL, 'Iodometric titration'),
  ('Sodium Polyacrylate', 0, 'Appearance', 'text', NULL, NULL, 'White granular powder', NULL, 'Visual'),
  ('Sodium Polyacrylate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Polyacrylate', 2, 'Water absorption', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Thiosulfate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Thiosulfate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Thiosulfate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Sodium Thiosulfate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sodium Thiosulfate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Spore Stain Kit (Schaeffer-Fulton)', 0, 'Appearance', 'text', NULL, NULL, 'Complete kit: malachite green, safranin', NULL, 'Visual'),
  ('Spore Stain Kit (Schaeffer-Fulton)', 1, 'Components', 'text', NULL, NULL, 'All components present and labelled', NULL, 'Visual'),
  ('Spore Stain Kit (Schaeffer-Fulton)', 2, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Starch', 0, 'Appearance', 'text', NULL, NULL, 'White fine powder', NULL, 'Visual'),
  ('Starch', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Starch', 2, 'Loss on drying', 'max', NULL, 15.0, NULL, '%', 'Gravimetric'),
  ('Starch', 3, 'Iodine test', 'text', NULL, NULL, 'Blue colour — passes', NULL, 'In-house'),
  ('Starch Soluble', 0, 'Appearance', 'text', NULL, NULL, 'White fine powder', NULL, 'Visual'),
  ('Starch Soluble', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Starch Soluble', 2, 'Solubility (2 % hot water)', 'text', NULL, NULL, 'Clear to slightly opalescent', NULL, 'Visual'),
  ('Starch Soluble', 3, 'Iodine test', 'text', NULL, NULL, 'Blue colour — passes', NULL, 'In-house'),
  ('Strontium Chloride', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Strontium Chloride', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Strontium Chloride', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Strontium Chloride', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Strontium Nitrate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Strontium Nitrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Strontium Nitrate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Strontium Nitrate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sucrose', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sucrose', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sucrose', 2, 'Loss on drying', 'max', NULL, 0.1, NULL, '%', 'Gravimetric'),
  ('Sucrose', 3, 'Solubility (10 % water)', 'text', NULL, NULL, 'Clear, colourless', NULL, 'Visual'),
  ('Sulfur', 0, 'Appearance', 'text', NULL, NULL, 'Yellow powder', NULL, 'Visual'),
  ('Sulfur', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sulfur', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Sulfur', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sulfur', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Tartaric Acid', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Tartaric Acid', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Tartaric Acid', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Tartaric Acid', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Tartaric Acid', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Trypsin', 0, 'Appearance', 'text', NULL, NULL, 'White to off-white powder', NULL, 'Visual'),
  ('Trypsin', 1, 'Activity', 'text', NULL, NULL, 'As stated on label', NULL, 'Enzymatic assay'),
  ('Toluene', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Toluene', 1, 'Assay', 'min', 99.5, NULL, NULL, '%', 'GC'),
  ('Toluene', 2, 'Water', 'max', NULL, 0.03, NULL, '%', 'Karl Fischer'),
  ('Toluene', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('Gallic Acid (3,4,5-Trihydroxybenzoic Acid)', 0, 'Appearance', 'text', NULL, NULL, 'White to pale fawn crystalline powder', NULL, 'Visual'),
  ('Gallic Acid (3,4,5-Trihydroxybenzoic Acid)', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Gallic Acid (3,4,5-Trihydroxybenzoic Acid)', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Tween 20 (Polysorbate 20)', 0, 'Appearance', 'text', NULL, NULL, 'Clear yellow viscous liquid', NULL, 'Visual'),
  ('Tween 20 (Polysorbate 20)', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Vanadium(V) Oxide', 0, 'Appearance', 'text', NULL, NULL, 'Yellow-orange to brown powder', NULL, 'Visual'),
  ('Vanadium(V) Oxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Vanadium(V) Oxide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Vanadium(V) Oxide', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('White Vinegar', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid, acetic odour', NULL, 'Visual'),
  ('White Vinegar', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('White Vinegar', 2, 'Acidity (as acetic acid)', 'range', 4.0, 6.0, NULL, '% w/v', 'Titration'),
  ('Voges-Proskauer Reagent (VP-B, 40% KOH)', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless solution', NULL, 'Visual'),
  ('Voges-Proskauer Reagent (VP-B, 40% KOH)', 1, 'KOH', 'range', 38.0, 42.0, NULL, '% w/v', 'Titration'),
  ('White Beeswax', 0, 'Appearance', 'text', NULL, NULL, 'White to yellowish-white waxy solid', NULL, 'Visual'),
  ('White Beeswax', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Xylene', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Xylene', 1, 'Assay', 'min', 98.5, NULL, NULL, '%', 'GC'),
  ('Xylene', 2, 'Water', 'max', NULL, 0.05, NULL, '%', 'Karl Fischer'),
  ('Xylene', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('Zinc Chloride Anhydrous', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Zinc Chloride Anhydrous', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Zinc Chloride Anhydrous', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Zinc Chloride Anhydrous', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Zinc Nitrate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Zinc Nitrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Zinc Nitrate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Zinc Nitrate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Zinc Granulated', 0, 'Appearance', 'text', NULL, NULL, 'Grey metal granules', NULL, 'Visual'),
  ('Zinc Granulated', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Zinc Granulated', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'In-house'),
  ('Zinc Sulfate Heptahydrate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Zinc Sulfate Heptahydrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Zinc Sulfate Heptahydrate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Zinc Sulfate Heptahydrate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Zinc Metal', 0, 'Appearance', 'text', NULL, NULL, 'Grey metal powder', NULL, 'Visual'),
  ('Zinc Metal', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Zinc Metal', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'In-house'),
  ('Aluminium Metal', 0, 'Appearance', 'text', NULL, NULL, 'Silvery-white metal (foil / powder / granules)', NULL, 'Visual'),
  ('Aluminium Metal', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Aluminium Metal', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'In-house'),
  ('Ammonium Nitrate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Ammonium Nitrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Ammonium Nitrate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Ammonium Nitrate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Ammonium Nitrate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Barium Acetate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Barium Acetate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Barium Acetate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Barium Acetate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Barium Chloride', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Barium Chloride', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Barium Chloride', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Barium Chloride', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Bromophenol Blue', 0, 'Appearance', 'text', NULL, NULL, 'Orange-pink to red-purple powder', NULL, 'Visual'),
  ('Bromophenol Blue', 1, 'Solubility', 'text', NULL, NULL, 'Clear solution in ethanol / water', NULL, 'Visual'),
  ('Bromophenol Blue', 2, 'Transition interval', 'text', NULL, NULL, 'pH 3.0 (yellow) – 4.6 (blue-violet)', NULL, 'pH titration'),
  ('Bromothymol Blue', 0, 'Appearance', 'text', NULL, NULL, 'Cream to pink powder', NULL, 'Visual'),
  ('Bromothymol Blue', 1, 'Solubility', 'text', NULL, NULL, 'Clear solution in ethanol / water', NULL, 'Visual'),
  ('Bromothymol Blue', 2, 'Transition interval', 'text', NULL, NULL, 'pH 6.0 (yellow) – 7.6 (blue)', NULL, 'pH titration'),
  ('Almond Oil', 0, 'Appearance', 'text', NULL, NULL, 'Clear pale yellow oil', NULL, 'Visual'),
  ('Almond Oil', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Carbomer', 0, 'Appearance', 'text', NULL, NULL, 'White fluffy powder', NULL, 'Visual'),
  ('Carbomer', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Carbomer', 2, 'pH (0.5 % dispersion)', 'range', 2.5, 3.5, NULL, '', 'pH meter'),
  ('Castor Oil', 0, 'Appearance', 'text', NULL, NULL, 'Clear pale yellow viscous oil', NULL, 'Visual'),
  ('Castor Oil', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Castor Oil', 2, 'Relative density (20 °C)', 'range', 0.952, 0.965, NULL, '', 'Density meter'),
  ('Cetyl Alcohol', 0, 'Appearance', 'text', NULL, NULL, 'White waxy flakes', NULL, 'Visual'),
  ('Cetyl Alcohol', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Cetyl Alcohol', 2, 'Melting point', 'range', 45.0, 52.0, NULL, '°C', 'Melting point apparatus'),
  ('Carboxymethyl Cellulose Sodium (CMC)', 0, 'Appearance', 'text', NULL, NULL, 'White to off-white granular powder', NULL, 'Visual'),
  ('Carboxymethyl Cellulose Sodium (CMC)', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Carboxymethyl Cellulose Sodium (CMC)', 2, 'pH (1 % solution)', 'range', 6.0, 8.5, NULL, '', 'pH meter'),
  ('Coffee Oil', 0, 'Appearance', 'text', NULL, NULL, 'Brown oil, characteristic coffee odour', NULL, 'Visual'),
  ('Coffee Oil', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Congo Red', 0, 'Appearance', 'text', NULL, NULL, 'Red-brown powder', NULL, 'Visual'),
  ('Congo Red', 1, 'Solubility', 'text', NULL, NULL, 'Clear solution in ethanol / water', NULL, 'Visual'),
  ('Congo Red', 2, 'Transition interval', 'text', NULL, NULL, 'pH 3.0 (blue) – 5.2 (red)', NULL, 'pH titration'),
  ('Copper Filings', 0, 'Appearance', 'text', NULL, NULL, 'Reddish-brown metal filings', NULL, 'Visual'),
  ('Copper Filings', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Copper Filings', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'In-house'),
  ('Copper(II) Hydroxide', 0, 'Appearance', 'text', NULL, NULL, 'Blue to blue-green powder', NULL, 'Visual'),
  ('Copper(II) Hydroxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Copper(II) Hydroxide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Copper(II) Hydroxide', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Copper(II) Bromide', 0, 'Appearance', 'text', NULL, NULL, 'Black to dark grey crystals', NULL, 'Visual'),
  ('Copper(II) Bromide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Copper(II) Bromide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Copper(II) Bromide', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Disodium Tetraborate (Borax)', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Disodium Tetraborate (Borax)', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Disodium Tetraborate (Borax)', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Disodium Tetraborate (Borax)', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Disodium Tetraborate (Borax)', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Fehling''s Solution B', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless solution', NULL, 'Visual'),
  ('Fehling''s Solution B', 1, 'Performance (mixed with A, glucose)', 'text', NULL, NULL, 'Red precipitate — passes', NULL, 'In-house'),
  ('Formalin (Formaldehyde Solution)', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Formalin (Formaldehyde Solution)', 1, 'Assay (HCHO)', 'range', 37.0, 40.0, NULL, '%', 'Titration'),
  ('Formic Acid', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Formic Acid', 1, 'Assay', 'min', 85.0, NULL, NULL, '%', 'Titration'),
  ('Giemsa Stain', 0, 'Appearance', 'text', NULL, NULL, 'Dark blue-violet solution', NULL, 'Visual'),
  ('Giemsa Stain', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Gelatin', 0, 'Appearance', 'text', NULL, NULL, 'Colourless to pale yellow granules / powder', NULL, 'Visual'),
  ('Gelatin', 1, 'Gel formation', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('n-Hexane', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('n-Hexane', 1, 'Assay', 'min', 99.0, NULL, NULL, '%', 'GC'),
  ('n-Hexane', 2, 'Water', 'max', NULL, 0.02, NULL, '%', 'Karl Fischer'),
  ('n-Hexane', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('1-Hexanol', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('1-Hexanol', 1, 'Assay', 'min', 98.0, NULL, NULL, '%', 'GC'),
  ('1-Hexanol', 2, 'Water', 'max', NULL, 0.2, NULL, '%', 'Karl Fischer'),
  ('1-Hexanol', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('Hydrochloric Acid', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless to faintly yellow fuming liquid', NULL, 'Visual'),
  ('Hydrochloric Acid', 1, 'Assay (HCl)', 'range', 35.0, 38.0, NULL, '%', 'Titration'),
  ('Immersion Oil', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless to pale yellow oil', NULL, 'Visual'),
  ('Immersion Oil', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Immersion Oil', 2, 'Refractive index (nD 23 °C)', 'range', 1.514, 1.516, NULL, '', 'Refractometer'),
  ('Iron Metal', 0, 'Appearance', 'text', NULL, NULL, 'Grey metal powder / filings', NULL, 'Visual'),
  ('Iron Metal', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Iron Metal', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'In-house'),
  ('Lead Metal', 0, 'Appearance', 'text', NULL, NULL, 'Bluish-grey metal', NULL, 'Visual'),
  ('Lead Metal', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Lead Metal', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'In-house'),
  ('Lime Water', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless solution', NULL, 'Visual'),
  ('Lime Water', 1, 'Performance (CO2)', 'text', NULL, NULL, 'Milky white precipitate — passes', NULL, 'In-house'),
  ('Magnesium Hydroxide', 0, 'Appearance', 'text', NULL, NULL, 'White powder', NULL, 'Visual'),
  ('Magnesium Hydroxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Magnesium Hydroxide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Magnesium Hydroxide', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Magnesium Hydroxide', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Magnesium Metal', 0, 'Appearance', 'text', NULL, NULL, 'Silvery ribbon / turnings', NULL, 'Visual'),
  ('Magnesium Metal', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Magnesium Metal', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'In-house'),
  ('Menthol Oil', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless oil, characteristic odour', NULL, 'Visual'),
  ('Menthol Oil', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Methyl Orange', 0, 'Appearance', 'text', NULL, NULL, 'Orange-yellow powder', NULL, 'Visual'),
  ('Methyl Orange', 1, 'Solubility', 'text', NULL, NULL, 'Clear solution in ethanol / water', NULL, 'Visual'),
  ('Methyl Orange', 2, 'Transition interval', 'text', NULL, NULL, 'pH 3.1 (red) – 4.4 (yellow)', NULL, 'pH titration'),
  ('Molisch Reagent', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless to pale yellow solution', NULL, 'Visual'),
  ('Molisch Reagent', 1, 'Performance (glucose)', 'text', NULL, NULL, 'Violet ring — passes', NULL, 'In-house'),
  ('Nutrient Agar', 0, 'Appearance', 'text', NULL, NULL, 'Light beige free-flowing powder', NULL, 'Visual'),
  ('Nutrient Agar', 1, 'pH of prepared medium (25 °C)', 'range', 6.6, 7.0, NULL, '', 'pH meter'),
  ('Nutrient Agar', 2, 'Growth promotion', 'text', NULL, NULL, 'Good growth of E. coli and S. aureus', NULL, 'Microbiological'),
  ('Nutrient Agar', 3, 'Sterility (prepared medium)', 'text', NULL, NULL, 'No growth', NULL, 'Incubation'),
  ('Orange Peel Powder', 0, 'Appearance', 'text', NULL, NULL, 'Orange-brown powder, characteristic odour', NULL, 'Visual'),
  ('Orange Peel Powder', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Oxalic Acid', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Oxalic Acid', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Oxalic Acid', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Oxalic Acid', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Oxalic Acid', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Paraffin Oil (Liquid Paraffin)', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless oily liquid, odourless', NULL, 'Visual'),
  ('Paraffin Oil (Liquid Paraffin)', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Paraffin Oil (Liquid Paraffin)', 2, 'Relative density (20 °C)', 'range', 0.827, 0.89, NULL, '', 'Density meter'),
  ('Phenol Red', 0, 'Appearance', 'text', NULL, NULL, 'Red crystalline powder', NULL, 'Visual'),
  ('Phenol Red', 1, 'Solubility', 'text', NULL, NULL, 'Clear solution in ethanol / water', NULL, 'Visual'),
  ('Phenol Red', 2, 'Transition interval', 'text', NULL, NULL, 'pH 6.8 (yellow) – 8.4 (red)', NULL, 'pH titration'),
  ('Phenolphthalein', 0, 'Appearance', 'text', NULL, NULL, 'White to faintly yellowish powder', NULL, 'Visual'),
  ('Phenolphthalein', 1, 'Solubility', 'text', NULL, NULL, 'Clear solution in ethanol / water', NULL, 'Visual'),
  ('Phenolphthalein', 2, 'Transition interval', 'text', NULL, NULL, 'pH 8.2 (colourless) – 10.0 (pink/red)', NULL, 'pH titration'),
  ('Phosphate (unspecified)', 0, 'Appearance', 'text', NULL, NULL, 'Conforms to description', NULL, 'Visual'),
  ('Phosphate (unspecified)', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Phosphate (unspecified)', 2, 'Specification', 'text', NULL, NULL, 'To be defined after identifying the exact phosphate', NULL, 'In-house'),
  ('Phosphoric Acid', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Phosphoric Acid', 1, 'Assay (H3PO4)', 'min', 85.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Metal', 0, 'Appearance', 'text', NULL, NULL, 'Soft silvery metal under mineral oil', NULL, 'Visual'),
  ('Potassium Metal', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Metal', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'In-house'),
  ('Potassium Thiocyanate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Potassium Thiocyanate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Thiocyanate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Thiocyanate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Potassium Thiocyanate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Povidone (PVP)', 0, 'Appearance', 'text', NULL, NULL, 'White to creamy-white powder', NULL, 'Visual'),
  ('Povidone (PVP)', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Povidone (PVP)', 2, 'pH (5 % solution)', 'range', 3.0, 7.0, NULL, '', 'pH meter'),
  ('Rosehip Oil', 0, 'Appearance', 'text', NULL, NULL, 'Clear golden-orange oil', NULL, 'Visual'),
  ('Rosehip Oil', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Rosewood Oil', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless to pale yellow oil, characteristic odour', NULL, 'Visual'),
  ('Rosewood Oil', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Saccharin', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Saccharin', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Saccharin', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Silica Gel Blue (Indicating)', 0, 'Appearance', 'text', NULL, NULL, 'Blue beads / granules', NULL, 'Visual'),
  ('Silica Gel Blue (Indicating)', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Silica Gel Blue (Indicating)', 2, 'Loss on drying', 'max', NULL, 5.0, NULL, '%', 'Gravimetric'),
  ('Silica Gel Blue (Indicating)', 3, 'Indicator colour change', 'text', NULL, NULL, 'Blue (dry) → pink (moist)', NULL, 'Visual'),
  ('Sodium Metal', 0, 'Appearance', 'text', NULL, NULL, 'Soft silvery metal under mineral oil', NULL, 'Visual'),
  ('Sodium Metal', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Metal', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'In-house'),
  ('Sodium Acetate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Acetate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Acetate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Sodium Acetate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sodium Acetate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sodium Bromide', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Bromide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Bromide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Sodium Bromide', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sodium Bromide', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sodium Iodide', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Iodide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Iodide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Sodium Iodide', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sodium Iodide', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sodium Nitrate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sodium Nitrate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sodium Nitrate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Sodium Nitrate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sodium Nitrate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Soft Paraffin (Vaseline)', 0, 'Appearance', 'text', NULL, NULL, 'White translucent unctuous mass', NULL, 'Visual'),
  ('Soft Paraffin (Vaseline)', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Spermaceti', 0, 'Appearance', 'text', NULL, NULL, 'White waxy solid', NULL, 'Visual'),
  ('Spermaceti', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('Strontium Oxide', 0, 'Appearance', 'text', NULL, NULL, 'White to greyish powder', NULL, 'Visual'),
  ('Strontium Oxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Strontium Oxide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Strontium Oxide', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sudan III Solution', 0, 'Appearance', 'text', NULL, NULL, 'Clear red-orange solution', NULL, 'Visual'),
  ('Sudan III Solution', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Sulfamic Acid', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Sulfamic Acid', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Sulfamic Acid', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Sulfamic Acid', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Sulfamic Acid', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Sulfuric Acid', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Sulfuric Acid', 1, 'Assay (H2SO4)', 'range', 95.0, 98.0, NULL, '%', 'Titration'),
  ('Thymolphthalein Indicator Solution', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless solution', NULL, 'Visual'),
  ('Thymolphthalein Indicator Solution', 1, 'Transition interval', 'text', NULL, NULL, 'pH 9.3 (colourless) – 10.5 (blue)', NULL, 'pH titration'),
  ('Tollens'' Reagent', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless solution (AgNO3 5 %)', NULL, 'Visual'),
  ('Tollens'' Reagent', 1, 'Performance (aldehyde)', 'text', NULL, NULL, 'Silver mirror — passes', NULL, 'In-house'),
  ('Trichloroacetic Acid', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Trichloroacetic Acid', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Trichloroacetic Acid', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Triethanolamine', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless to pale yellow viscous liquid', NULL, 'Visual'),
  ('Triethanolamine', 1, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Xanthan Gum', 0, 'Appearance', 'text', NULL, NULL, 'White to cream powder', NULL, 'Visual'),
  ('Xanthan Gum', 1, 'Odour', 'text', NULL, NULL, 'Characteristic', NULL, 'Organoleptic'),
  ('XLD Agar', 0, 'Appearance', 'text', NULL, NULL, 'Pink-beige free-flowing powder', NULL, 'Visual'),
  ('XLD Agar', 1, 'pH of prepared medium (25 °C)', 'range', 7.2, 7.6, NULL, '', 'pH meter'),
  ('XLD Agar', 2, 'Growth promotion', 'text', NULL, NULL, 'Salmonella: red colonies with black centres; E. coli: yellow colonies', NULL, 'Microbiological'),
  ('XLD Agar', 3, 'Sterility (prepared medium)', 'text', NULL, NULL, 'No growth', NULL, 'Incubation'),
  ('Yeast', 0, 'Appearance', 'text', NULL, NULL, 'Light brown granules', NULL, 'Visual'),
  ('Yeast', 1, 'Viability (fermentation of sugar)', 'text', NULL, NULL, 'Gas produced — passes', NULL, 'In-house'),
  ('Zinc Acetate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Zinc Acetate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Zinc Acetate', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Zinc Acetate', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Zinc Oxide', 0, 'Appearance', 'text', NULL, NULL, 'White fine powder', NULL, 'Visual'),
  ('Zinc Oxide', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Zinc Oxide', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Zinc Oxide', 3, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Distilled Water', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Distilled Water', 1, 'pH', 'range', 5.0, 7.0, NULL, '', 'pH meter'),
  ('Distilled Water', 2, 'Conductivity', 'max', NULL, 5, NULL, 'µS/cm', 'Conductivity meter'),
  ('Potassium Sodium Tartrate Tetrahydrate (Rochelle Salt)', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Potassium Sodium Tartrate Tetrahydrate (Rochelle Salt)', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Sodium Tartrate Tetrahydrate (Rochelle Salt)', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Sodium Tartrate Tetrahydrate (Rochelle Salt)', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Potassium Sodium Tartrate Tetrahydrate (Rochelle Salt)', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('p-Dimethylaminobenzaldehyde', 0, 'Appearance', 'text', NULL, NULL, 'White to pale yellow crystalline powder', NULL, 'Visual'),
  ('p-Dimethylaminobenzaldehyde', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('p-Dimethylaminobenzaldehyde', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Isoamyl Alcohol', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Isoamyl Alcohol', 1, 'Assay', 'min', 98.5, NULL, NULL, '%', 'GC'),
  ('Isoamyl Alcohol', 2, 'Water', 'max', NULL, 0.2, NULL, '%', 'Karl Fischer'),
  ('Isoamyl Alcohol', 3, 'Residue on evaporation', 'max', NULL, 0.005, NULL, '%', 'Gravimetric'),
  ('alpha-Naphthol', 0, 'Appearance', 'text', NULL, NULL, 'White to off-white crystals', NULL, 'Visual'),
  ('alpha-Naphthol', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('alpha-Naphthol', 2, 'Assay', 'min', 98.0, NULL, NULL, '%', 'Titration'),
  ('Basic Fuchsin', 0, 'Appearance', 'text', NULL, NULL, 'Dark green crystals with metallic lustre', NULL, 'Visual'),
  ('Basic Fuchsin', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Methylene Blue', 0, 'Appearance', 'text', NULL, NULL, 'Dark green crystals / powder', NULL, 'Visual'),
  ('Methylene Blue', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Safranin O', 0, 'Appearance', 'text', NULL, NULL, 'Reddish-brown powder', NULL, 'Visual'),
  ('Safranin O', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Eosin Y', 0, 'Appearance', 'text', NULL, NULL, 'Red powder', NULL, 'Visual'),
  ('Eosin Y', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Sudan III', 0, 'Appearance', 'text', NULL, NULL, 'Reddish-brown powder', NULL, 'Visual'),
  ('Sudan III', 1, 'Staining performance', 'text', NULL, NULL, 'Passes (typical staining reactions on control smear)', NULL, 'Microscopy'),
  ('Litmus', 0, 'Appearance', 'text', NULL, NULL, 'Blue granules / powder', NULL, 'Visual'),
  ('Litmus', 1, 'Solubility', 'text', NULL, NULL, 'Clear solution in ethanol / water', NULL, 'Visual'),
  ('Litmus', 2, 'Transition interval', 'text', NULL, NULL, 'pH 4.5 (red) – 8.3 (blue)', NULL, 'pH titration'),
  ('Thymolphthalein', 0, 'Appearance', 'text', NULL, NULL, 'White to off-white powder', NULL, 'Visual'),
  ('Thymolphthalein', 1, 'Solubility', 'text', NULL, NULL, 'Clear solution in ethanol / water', NULL, 'Visual'),
  ('Thymolphthalein', 2, 'Transition interval', 'text', NULL, NULL, 'pH 9.3 (colourless) – 10.5 (blue)', NULL, 'pH titration'),
  ('Potassium Dihydrogen Phosphate', 0, 'Appearance', 'text', NULL, NULL, 'White crystalline powder', NULL, 'Visual'),
  ('Potassium Dihydrogen Phosphate', 1, 'Identification', 'text', NULL, NULL, 'Passes test', NULL, 'In-house'),
  ('Potassium Dihydrogen Phosphate', 2, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Potassium Dihydrogen Phosphate', 3, 'Heavy metals (as Pb)', 'max', NULL, 0.002, NULL, '%', 'Colorimetric'),
  ('Potassium Dihydrogen Phosphate', 4, 'Iron (Fe)', 'max', NULL, 0.005, NULL, '%', 'Colorimetric'),
  ('Bromine', 0, 'Appearance', 'text', NULL, NULL, 'Dark red-brown fuming liquid', NULL, 'Visual'),
  ('Bromine', 1, 'Assay', 'min', 99.0, NULL, NULL, '%', 'Titration'),
  ('Mercury', 0, 'Appearance', 'text', NULL, NULL, 'Silvery liquid metal', NULL, 'Visual'),
  ('Mercury', 1, 'Assay', 'min', 99.9, NULL, NULL, '%', 'In-house'),
  ('Ethanol 95%', 0, 'Appearance', 'text', NULL, NULL, 'Clear colourless liquid', NULL, 'Visual'),
  ('Ethanol 95%', 1, 'Ethanol content', 'range', 94.0, 96.0, NULL, '% v/v', 'Alcoholmeter / GC');

-- المواد اللي رح تاخد مسودة = اللي ما إلها ولا بند
CREATE TEMP TABLE _targets ON COMMIT DROP AS
  SELECT m.id, m.name_en FROM public.chem_materials m
  WHERE NOT EXISTS (SELECT 1 FROM public.chem_specs s WHERE s.material_id = m.id)
    AND EXISTS (SELECT 1 FROM _draft_specs d WHERE lower(d.name) = lower(m.name_en));

INSERT INTO public.chem_specs (material_id, seq, parameter, spec_type, min_value, max_value, text_value, unit, method)
SELECT t.id, d.seq, d.parameter, d.spec_type, d.min_value, d.max_value, d.text_value, NULLIF(d.unit,''), d.method
FROM _targets t JOIN _draft_specs d ON lower(d.name) = lower(t.name_en);

UPDATE public.chem_materials SET specs_reviewed = false WHERE id IN (SELECT id FROM _targets);

INSERT INTO public.changelog_entries (title, description)
SELECT '📋 الكيماويات: مسودة مواصفات الفحص', 'أُضيفت مواصفات فحص نموذجية لكل المواد (المظهر، التعريف، النقاوة، الشوائب، وفحوصات الأداء للمحاليل والصبغات والأوساط) كنقطة بداية لشهادات التحليل — معلّمة "بانتظار المراجعة" لحد ما مسؤول المختبر يراجع كل مادة ويعتمدها.'
WHERE NOT EXISTS (SELECT 1 FROM public.changelog_entries WHERE title = '📋 الكيماويات: مسودة مواصفات الفحص');

COMMIT;

SELECT count(*) FILTER (WHERE NOT specs_reviewed) AS pending_review, count(*) AS materials,
       (SELECT count(*) FROM public.chem_specs) AS spec_rows FROM public.chem_materials;
